const galleryData = [
  { src: "../../gallery/1.jpeg", alt: "1" },
  { src: "../../gallery/2.jpeg", alt: "2" },
  { src: "../../gallery/3.jpg", alt: "3" },
  { src: "../../gallery/4.jpeg", alt: "4" },
  { src: "../../gallery/5.jpeg", alt: "5" },
  { src: "../../gallery/6.jpeg", alt: "6" },
  { src: "../../gallery/7.jpeg", alt: "7" },
  { src: "../../gallery/8.jpeg", alt: "8" },
  { src: "../../gallery/9.jpeg", alt: "9" },
  { src: "../../gallery/10.jpeg", alt: "10" },
  { src: "../../gallery/11.jpg", alt: "11" },
  { src: "../../gallery/12.jpeg", alt: "12" },
  { src: "../../gallery/13.jpg", alt: "13" },
  { src: "../../gallery/14.jpeg", alt: "14" },
  { src: "../../gallery/15.jpg", alt: "15" },
  { src: "../../gallery/16.png", alt: "16" },
  { src: "../../gallery/17.jpeg", alt: "17" },
  { src: "../../gallery/18.jpeg", alt: "18" },
  { src: "../../gallery/19.jpg", alt: "19" },
  { src: "../../gallery/20.jpeg", alt: "20" },
  { src: "../../gallery/21.jpeg", alt: "21" },
  { src: "../../gallery/22.jpeg", alt: "22" },
  { src: "../../gallery/23.png", alt: "23" },
  { src: "../../gallery/24.jpeg", alt: "24" },
  { src: "../../gallery/25.jpg", alt: "25" },
  { src: "../../gallery/26.jpeg", alt: "26" },
  { src: "../../gallery/27.jpeg", alt: "27" },
];

export default galleryData;
